config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :entries
  patch 'entries', controller: :entries, action: :update, as: :journal_entry
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
	validates_presence_of :field_1, :field_2, :field_3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@entries = JournalEntry.all
		@entries = @entries.order(:created_at)

		@today = Date.today
	end

	def new
		@today = Date.today
	end

	def edit
		@entry = JournalEntry.find(params[:id])
		
		@today = @entry.created_at
	end

	def create
		permitted_params = params.permit(:field_1, :field_2, :field_3, :field_4, :field_5, :field_6)

		@entry = JournalEntry.create(permitted_params)

		if @entry.persisted?
			redirect_to entries_path
		else
			render :new
		end
	end

  def update
    # Process the incoming data
    permitted_params = params.require(:journal_entry).permit(:field_1, :field_2, :field_3, :field_4, :field_4, :field_5, :field_6)
    # params = {"field_1"=>"", "field_2"=>"", "field_3"=>"", "field_4"=>"", "field_5"=>"", "field_6"=>""}
    # Find the existing journal entry in the database
    @entry = JournalEntry.find(params[:id]) #params[:id] is pulled from the URL
    # We update our entry, and if no errors, redirect to entries_path
    if @entry.update(permitted_params) # this line saves the record and then checks if it went well.
    # If so, it redirects to index page if the creation was successful
      redirect_to entries_path # You can find this helper by executing the "rails routes" command in your terminal
    else
    # Refresh the page and specifiy an error if the creation was unsuccesful
      @day = @entry.created_at
      render :edit # This is the simplest way to reload the page, while keeping our entries
    end
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/edit.html.erb
<h1 class="page-title">New Entry for <%=@today.strftime('%a %-d %B')%></h1>
<%= form_with model: @entry, method: :patch, class: 'flex flex-column entry-form' do |form| %>
<%= link_to 'Back to entries', entries_path, class: 'page-title' %>
<h2>Morning</h2>
<%= form.label :field_1, "3 things I'm grateful for :" %><br>
<%= form.text_area :field_1 %><br>
<%= form.label :field_2, "3 positive affirmations :" %><br>
<%= form.text_area :field_2 %><br>
<%= form.label :field_3, "What's my main focus right now ?" %><br>
<%= form.text_area :field_3 %><br>
<h2>Evening</h2>
<%= form.label :field_4, "3 things that were positive today :" %><br>
<%= form.text_area :field_4 %><br>
<%= form.label :field_5, "1 thing I could have done better ? :" %><br>
<%= form.text_area :field_5 %><br>
<%= form.label :field_6, "3 things I wanna accomplish tomorrow :" %><br>
<%= form.text_area :field_6 %><br>
<%= form.submit "Submit", class:'primary-button full-button' %>
<% end %>

app/views/entries/index.html.erb
<div class="flex flex-row justify-around">
	<h1><%= @today.strftime("%A %-m %B") %></h1>
	<%= link_to '/entries/new' do %>
		<button class="primary-button">New Entry</button>
	<% end %>
</div>
<div class="flex flex-column justify-around align-items-center mt-50">
	<% if @entries.empty? %>
		<h3>No entries</h3>
	<% else %>
		<% @entries.each do |entry| %>
			<div class="entry">
				<%= link_to "Journal entry ##{entry.id}", edit_entry_path(entry) %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/entries/new.html.erb
<h1>New Entry for <%=@today.strftime('%a %-d %B')%></h1>

<%= form_with url: "/entries", method: :post, class: 'flex flex-column entry-form' do |form| %>
	<h2>Morning</h2>

	<%= form.label :field_1, "3 things I'm grateful for :" %><br>
	<%= form.text_area :field_1 %><br>
	<%= form.label :field_2, "3 positive affirmations :" %><br>
	<%= form.text_area :field_2 %><br>
	<%= form.label :field_3, "What's my main focus right now ? :" %><br>
	<%= form.text_area :field_3 %><br>

<h2>Evening</h2>
	
	<%= form.label :field_4, "3 things that were positive today :" %><br>
	<%= form.text_area :field_4 %><br>
	<%= form.label :field_5, "1 thing I could have done better :" %><br>
	<%= form.text_area :field_5 %><br>
	<%= form.label :field_6, "3 things I wanna accomplish tomorrow :" %><br>
	<%= form.text_area :field_6 %><br>
	<%= form.submit "Submit", class:'primary-button full-button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SevenDaysRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>